
  CREATE TABLE ANGAJATI (
	id INT GENERATED BY DEFAULT AS IDENTITY,
	nume varchar(255) not null,
	prenume varchar(255) not null,
	id_functie int not null
);

  CREATE TABLE CONSULTATII_MEDICALE (
  id INT GENERATED BY DEFAULT AS IDENTITY,
  data TIMESTAMP not null,
  id_angajat INT not null
  );

  CREATE TABLE CURSANTI (
	id INT GENERATED BY DEFAULT AS IDENTITY,
	numar_cursanti INT not null,
	nivel_cunostinte varchar(255) not null
);

  CREATE TABLE CURSURI (
	id INT GENERATED BY DEFAULT AS IDENTITY,
	nume_curs varchar(255) not null
);

  CREATE TABLE CV (
	id INT GENERATED BY DEFAULT AS IDENTITY,
	adresa varchar(255) not null,
	telefon int not null,
	email varchar(255) not null,
	nationalitate varchar(255) not null,
	data_nastere varchar(255) not null,
	sex varchar(255) not null,
	oras varchar(255) not null,
	tara varchar(255) not null,
	nume varchar(255) not null,
	prenume varchar(255) not null
);

  CREATE TABLE DEPARTAMENTE (
	id INT GENERATED BY DEFAULT AS IDENTITY,
	nume varchar(255) not null
);

  CREATE TABLE EDUCATIE (
	id INT GENERATED BY DEFAULT AS IDENTITY,
	descriere varchar(255) not null,
	id_cv INT not null,
	an_absolvire int not null,
	facultate varchar(255) not null,
	ani_facultate INT not null
);

  CREATE TABLE EXPERIENTA (
	id INT GENERATED BY DEFAULT AS IDENTITY,
	descriere varchar(255) not null,
	id_cv int not null,
	experienta_anterioara varchar(255) not null,
	angajator varchar(255) not null,
	pozitii_ocupate varchar(255) not null,
	ani_experienta int not null,
	limbi_vorbite varchar(255) not null
);

  CREATE TABLE FUNCTII (
	id INT GENERATED BY DEFAULT AS IDENTITY,
	nume_functie varchar(255) not null,
	salariu int not null,
	id_departament int not null
);

  CREATE TABLE LOGIN (
	id_angajat INT GENERATED BY DEFAULT AS IDENTITY,
	nume_utilizator varchar(255) not null,
	parola varchar(255) not null
);

  CREATE TABLE PLANIFICARE_CONCEDII (
	id INT GENERATED BY DEFAULT AS IDENTITY,
	tip_concediu varchar(255) not null,
	data TIMESTAMP not null,
	id_angajat int not null
);

  CREATE TABLE PROGRAMARE_CURSURI (
	id INT GENERATED BY DEFAULT AS IDENTITY,
	data TIMESTAMP not null,
	id_cursanti int not null
);

create SEQUENCE Departamente_seq start with 1 increment by 1;
create SEQUENCE PosturiDisponibile_seq start with 1 increment by 1;
create SEQUENCE Functii_seq start with 1 increment by 1;
create SEQUENCE Educatie_seq start with 1 increment by 1;
create SEQUENCE Experienta_seq start with 1 increment by 1;
create SEQUENCE Cv_seq start with 1 increment by 1;
create SEQUENCE ConsultatiiMedicale_seq start with 1 increment by 1;
create SEQUENCE Cursuri_seq start with 1 increment by 1;
create SEQUENCE ProgramareCursuri_seq start with 1 increment by 1;
create SEQUENCE Cursanti_seq start with 1 increment by 1;
create SEQUENCE Login_seq start with 1 increment by 1;
create SEQUENCE PlanificareConcedii_seq start with 1 increment by 1;
create SEQUENCE Angajati_seq start with 1 increment by 1;


INSERT INTO DEPARTAMENTE(nume) VALUES ('IT');
INSERT INTO DEPARTAMENTE(nume) VALUES ('Logistica');
INSERT INTO DEPARTAMENTE(nume) VALUES ('HR');
INSERT INTO DEPARTAMENTE(nume) VALUES ('Contabilitate');
INSERT INTO DEPARTAMENTE(nume) VALUES ('Marketing');

INSERT INTO CURSURI(nume_curs) VALUES ('Curs Java');
INSERT INTO CURSURI(nume_curs) VALUES ('Curs Baze de date');
INSERT INTO CURSURI(nume_curs) VALUES ('Curs C++');
INSERT INTO CURSURI(nume_curs) VALUES ('Curs Basic Java');
INSERT INTO CURSURI(nume_curs) VALUES ('Curs POO');

INSERT INTO CV(adresa,telefon, email,nationalitate, data_nastere, sex, oras, tara, nume, prenume) VALUES
('Str Moxa',0755412451, 'abc@gmail.com', 'romana', '22.02.1987', 'masculin', 'Bucuresti', 'Romania', 'Marian', 'Mihai');

INSERT INTO CV(adresa,telefon, email,nationalitate, data_nastere, sex, oras, tara, nume, prenume) VALUES
('Str M Eminescu',0758646858, 'cde@gmail.com', 'romana', '21.03.1933', 'masculin', 'Bucuresti', 'Romania', 'Popescu', 'Andrei');

INSERT INTO CV(adresa,telefon, email,nationalitate, data_nastere, sex, oras, tara, nume, prenume) VALUES
('Str Ion Creanga',0743251497, 'fgh@gmail.com', 'romana', '15.07.1977', 'feminin', 'Iasi', 'Romania', 'Ionescu', 'Marius');

INSERT INTO CURSANTI(numar_cursanti, nivel_cunostinte) VALUES (20, 'medii');
INSERT INTO CURSANTI(numar_cursanti, nivel_cunostinte) VALUES (15, 'incepatori');
INSERT INTO CURSANTI(numar_cursanti, nivel_cunostinte) VALUES (10, 'avansati');

INSERT INTO EDUCATIE(descriere, id_cv, an_absolvire, facultate, ani_facultate) VALUES ('descriere 1', 1,2007, 'CSIE', 3);
INSERT INTO EDUCATIE(descriere, id_cv, an_absolvire, facultate, ani_facultate) VALUES ('descriere 2', 2,2007, 'REI', 3);
INSERT INTO EDUCATIE(descriere, id_cv, an_absolvire, facultate, ani_facultate) VALUES ('descriere 3', 3,2007, 'CSIE', 3);

INSERT INTO EXPERIENTA(descriere, id_cv, experienta_anterioara, angajator, pozitii_ocupate, ani_experienta, limbi_vorbite)
VALUES ('descriere 1', 1, 'experienta 1', 'IMB', 'programator', 2, 'engleza, franceza');
INSERT INTO EXPERIENTA(descriere, id_cv, experienta_anterioara, angajator, pozitii_ocupate, ani_experienta, limbi_vorbite)
VALUES ('descriere 2', 2, 'experienta 2', 'Crystal System', 'programator', 2, 'engleza, franceza');
INSERT INTO EXPERIENTA(descriere, id_cv, experienta_anterioara, angajator, pozitii_ocupate, ani_experienta, limbi_vorbite)
VALUES ('descriere 3', 3, 'experienta 3', 'Crystal System', 'programator', 5, 'engleza, franceza');
