



  CREATE TABLE DEPARTAMENTE
   (	"ID" NUMBER, 
	"NUME" VARCHAR2(20 BYTE)
   )


INSERT INTO DEPARTAMENTE(id, nume) VALUES (1, 'IT');
INSERT INTO DEPARTAMENTE(id, nume) VALUES (2, 'Logistica');
INSERT INTO DEPARTAMENTE(id, nume) VALUES (3, 'HR');
INSERT INTO DEPARTAMENTE(id, nume) VALUES (4, 'Contabilitate');
INSERT INTO DEPARTAMENTE(id, nume) VALUES (5, 'Marketing');